import React, { useEffect } from 'react';
import { useLocation } from 'react-router-dom';

const Terms = () => {
    const location = useLocation();
    useEffect(() => {
      window.scrollTo(0, 0);
    }, [location]);
  
  return (
    <div className="max-w-screen-lg mx-auto px-4 py-8 text-wrap">
      <h1 className="text-3xl font-semibold mb-6">Terms & Conditions</h1>
      <section className="space-y-6 text-gray-800">
        <p>
          <strong>OVERVIEW</strong><br />
          This domain name www.foxpilots.in (hereinafter referred to as "Website") and App Rowdy on Google Playstore is owned and operated by ROWDYWEAR PRIVATE LIMITED, a Company incorporated under the provisions of the Companies Act 2013, having its registered office at Plot No.555/A Road No. 28, Jubilee Hills, Hyderabad TG 500033 IN (hereinafter referred to as "the Company").
        </p>

        <p>
          This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </p>

        <p>
          These terms and conditions constitute a legally binding agreement between you ("User") and the Company regarding the use of the App/Website. The Services to the User through the Website/App shall be bound by these terms and conditions.
        </p>

        <p>
          These terms and conditions of the Website/App are subject to periodic update and revision. The Company maintains the right to delete or modify information on this Website/App without prior notice. Please read these terms and conditions carefully before using the Website/App. If User does not agree to terms and conditions of this agreement, then User shall not use the Website/App.
        </p>

        <h2 className="text-xl font-semibold mt-6">ONLINE STORE TERMS</h2>
        <p>
          Use of the Website/App, is available only to persons who can form legally binding contracts. Users who are under the age of 18 years are not eligible to use this Website/App. If the User is under the age of 18 years and wish to use the Website/App, such use or transaction may be made by User's legal guardian or parents on the Website/App. The Company reserves the right to terminate Users registration and refuse to provide the services to the User, if it is brought to the Company notice or if it is discovered that the User is under the age of 18 years.
        </p>

        <p>
          User shall not use the products sold by the Company through the Website/App for any illegal or unauthorized purpose. User shall not transmit in the Website/App any worms, virus or any code of destructive nature. A breach or violation of any of the terms will result in an immediate termination of your use of the Website/App.
        </p>

        <h2 className="text-xl font-semibold mt-6">GENERAL CONDITIONS</h2>
        <p>
          Registration of the User is necessary on the Website/App to use the services provided by the Company. User shall be required to register for an account on the Website/App by providing email address, name, password and user name and other bank details as required by the Website/App for the processing the Payment. User shall provide accurate, complete and updated information in order to register on the Website/App to use the services.
        </p>

        <p>
          By submitting their phone number and email on the website/App, User agrees to receive any promotional messages from the company informing user about services or events related to the company.
        </p>

        <p>
          When User places an order to purchase a product from Website/App, the User shall receive an e-mail/message confirming receipt of the order and contain the details of the Users order (the "Order Confirmation E-mail"). The Order Confirmation E-mail is acknowledgement that the Company has received the Users order. Once the product is dispatched an e-mail confirmation is sent to the User of the dispatch (the "Dispatch Confirmation E-mail"). User can cancel their orders for a product subject to the cancellation policy.
        </p>

        <h2 className="text-xl font-semibold mt-6">Third Party Sites</h2>
        <p>
          The Company shall not be liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party Websites/App. User shall review carefully the third-party's policies and practices and make sure the User understand them before engaging in any transaction. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party.
        </p>

        <h2 className="text-xl font-semibold mt-6">Indemnification</h2>
        <p>
          User agrees to indemnify and hold the Company, its affiliates, officers, agents, employees, and partners harmless for and against any and all claims, liabilities, damages (actual and consequential), losses and expenses (including attorneys' fees) arising from or in any way related to any third party or claims relating to User's violation of these terms. In the event of such a claim, suit, or action, the Company shall provide notice of the claim to the contact information provided by the User during registration on the Website/App. Failure to deliver such notice shall not eliminate or reduce User's indemnification obligations.
        </p>

        <h2 className="text-xl font-semibold mt-6">Governing Law</h2>
        <p>
          These terms and condition and any separate agreements whereby the Company provides Users services shall be governed by and construed in accordance with the laws of India and jurisdiction of Hyderabad, Telangana.
        </p>

        <h2 className="text-xl font-semibold mt-6">Contact</h2>
        <p>
          Any queries about the terms of the agreement should be sent to the Company at hey@foxpilots.in
        </p>
      </section>
    </div>
  );
};

export default Terms;
